### PR TITLE
Update the pixel_shader usage of OnDiskBitmap

### PR DESCRIPTION
**Pull request by lesamouraipourpre**
OnDiskBitmap has had incompatible changes in `7.0.0-alpha.3` - Ref: https://github.com/adafruit/circuitpython/pull/4823
This PR is part of a group of updates for this change - https://github.com/adafruit/circuitpython/issues/4982

This PR updates the library to the combined usage for CP6 & CP7 with a TODO to remove the CP6 compatibility in the future. An example was added `examples/turtle_bgpic_changeturtle.py` that calls the methods that use OnDiskBitmap for testing.

It has been tested on a PyPortal with `6.3.0` and `7.0.0-alpha.4`

### CODE REVIEW

**Review by jepler — APPROVED** [review]
Looks good, thanks!  I did not test.

**Comment by FoamyGuy** [comment]
Something seems odd in this library. I tested the new `turtle_bgpic_changeturtle.py` example using a PyPortal with both `6.3.0` and `7.0.0-alpha.4`

On `6.3.0` using the currently released version of the library it outputs like this: 
image

On `7.0.0-alpha.4` using the version from this PR it looks like this:
image

The blue color for the lines doesn't seem to be getting used properly, and the stamp in the center gets "filled in" by the lines instead of being drawn on top of like in the other version.

Nothing problematic really jumps out about the changes from this PR though so I'm a bit stumped as to what could be causing this difference at first glance. 

I will try to take deeper look through the library code to see if I can figure out what is going on this weekend. I tested a few of the other examples (but not all) and didn't notice any issues with them so I am thinking perhaps this issues is related specifically to using `changeturtle()` to set an image as the turtle pen.

**Comment by FoamyGuy** [comment]
I never did get back into it. 

I am taking a closer look today.

**Review by FoamyGuy — APPROVED** [review]
I re-tested this PR with PyPortal  `7.2.0-rc.0` and `7.1.1`

And I am not seeing the weird behavior from my second image above anymore. That seems to have been resolved in the interim in the core or somewhere other than this library.

The changes here look good to me.

By now I think we are okay to remove the CP 6 fallback and I think it would also be okay to remove the now-artificial limitation on things added to the addon_group. I'll make a follow up PR for those.

**Pull request merged**
